name: deployment_env
channels:
  - pytorch
  - conda-forge
  - defaults # Keep defaults explicitly as per Conda's FutureWarning suggestion
dependencies:
  - python=3.9
  - cmake # Often a build dependency for ML libraries, good to keep
  - numpy # Added explicitly for interpolation-based resampling
  - pytorch # Assuming your ONNX models originate from PyTorch
  - torchvision # If you're working with torchvision models
  - cpuonly # For PyTorch on CPU (relevant if you don't have a supported GPU for PyTorch on Mac)
  - pip
  - pip:
    - tensorflow==2.13.0 # The full TensorFlow package for conversion
    - onnx==1.13.0       # Updated to resolve protobuf conflict with TensorFlow 2.13.0
    - onnxruntime==1.12.0 # Compatible with ONNX 1.13.0 and Python 3.9
    - onnx-tf==1.9.0     # Compatible with Python 3.9. Note: its compatibility with TensorFlow 2.13.0 might be a point of attention, but start here.